version: "3"

services:
  backend:
    container_name: backend
    restart: always
    image: kevcalderon/backnode_practica2
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    restart: always
    image: kevcalderon/front_practica2
    ports:
      - "3000:80"
    depends_on:
      - backend
    links:
      - backend